### ISSUE TITLE
Moving values into fortify macro

### ISSUE THREAD

**Issue by klotzambein** [dzamkov/fortify#1]
I have started using this crate for a project. So far it has been going great. However, I ran into an issue needing to move a value into the `fortify!` macro.

The following code does not compile:
```rust
use fortify::{fortify, Fortify, WithLifetime};

#[derive(WithLifetime)]
pub struct I32<'a> {
    foo: &'a i32,
}

pub fn create<'a>(foo: i32) -> Fortify<I32<'a>> {
    fortify! {
        let foo = foo;
        yield I32 { foo: &foo };
    }
}
```

This can probably be fixed by changing the closure and async block to move blocks. However, this might be a breaking change. I have worked around this issue by manually writing the macros contents and changing the blocks to move blocks.

**Comment by dzamkov** [comment]
[Fixed](https://github.com/dzamkov/fortify/commit/765a02160ccae287ad2fb5c0ef2884c160f84002) by changing the macro to use `move` closures. This is indeed a breaking change, but it's much easier to turn moves into borrows than vice versa. We're early enough in the project that getting things right is more important than keeping things stable.

This will be in the `0.3.0` release in a day or two.
